spring:
  application:
    name: scarlet
  profiles:
    active: dev

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 604800 # 2h
  refresh-token-expiration: 604800 # 7d

scarlet:
  default-word: world

scheduler:
  jobs:
    daily-word:
      cron: '0/30 * * * * *'
