###############################
# Application Properties File #
###############################

# Spring Boot
spring:
  application:
    name: scarlet
  profiles:
    active: dev
  jpa:
    open-in-view: false
  data:
    jpa:
      repositories:
        enabled: true
    redis:
      repositories:
        enabled: false

# App specific configuration
scarlet:
  default-word: world
  refresh-token-cookie-duration: 604800 # 7d

# JSON Web Token authorization
jwt:
  secret: ${JWT_SECRET}
  access-token-duration: 600 # 10m
  refresh-token-duration: 604800 # 7d

# Job scheduling
scheduler:
  jobs:
    auto-random-word:
      cron: '0 0 0 * * *'
    remove-old-refresh-tokens:
      cron: '0 0 0 * * *'
      refresh-token-lifecycle: 604800 # 7d

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
  default-consumes-media-type: application/json

# Logging
logging:
  file:
    name: /app/logs/scarlet.log
  level:
    root: info
