spring:
  application:
    name: scarlet
  profiles:
    active: dev
  jpa:
    open-in-view: false
  data:
    jpa:
      repositories:
        enabled: true
    redis:
      repositories:
        enabled: false

jwt:
  secret: ${JWT_SECRET}
  access-token-duration: 600 # 10m
  refresh-token-duration: 604800 # 7d

scarlet:
  default-word: world
  refresh-token-cookie-duration: 604800

scheduler:
  jobs:
    daily-word:
      cron: '0 0 0 * * *'
springdoc:
  api-docs:
    path: /api-docs
