###############################
# Application Properties File #
#         DEVELOPMENT         #
###############################

# Spring Boot
spring:
  datasource:
    url: jdbc:${DATABASE_TYPE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# App specific configuration
scarlet:
  refresh-token-cookie-duration: 900000 # 2m

# JSON Web Token authorization
jwt:
  secret: ${JWT_SECRET}
  access-token-duration: 90000 # 1m
  refresh-token-duration: 900000 # 2m

# Job scheduling
scheduler:
  jobs:
    auto-random-word:
      cron: '0 0 0 * * *'
    remove-old-refresh-tokens:
      cron: '0 0 0 * * *'
      refresh-token-lifecycle: 900000 # 2m

# Logging
logging:
  file:
    name: /app/logs/scarlet-dev.log
  level:
    root: info